

class FaultCodeData{
   String id;
   String? faultCode;
   String? title;

  FaultCodeData({required this.id,this.faultCode,this.title});
}

 List<FaultCodeData> dataFaultCode =[
   FaultCodeData(id: '0 ',faultCode: "None",title : "None" ),
   FaultCodeData(id: '1 ',faultCode: "P0010",title : "A camshaft position actuator circuit (bank 1)" ),
   FaultCodeData(id: '2 ',faultCode: "P0011",title : "A camshaft position - timing over advanced or system performance (Bank 1)" ),
   FaultCodeData(id: '3 ',faultCode: "P0012",title : "A camshaft position - timing over retarded (Bank 1)" ),
   FaultCodeData(id: '4 ',faultCode: "P0013",title : "B camshaft position - actuator circuit (Bank 1)" ),
   FaultCodeData(id: '5 ',faultCode: "P0014",title : "B camshaft position - timing over advanced or system performance (Bank 1)" ),
   FaultCodeData(id: '6 ',faultCode: "P0015",title : "B camshaft position - timing over retarded (Bank 1)" ),
   FaultCodeData(id: '7 ',faultCode: "P0016",title : "Crankshaft Position Camshaft Position Correlation Bank 1 Sensor A" ),
   FaultCodeData(id: '8 ',faultCode: "P0020",title : "A camshaft position actuator circuit (Bank 2)" ),
   FaultCodeData(id: '9 ',faultCode: "P0021",title : "A camshaft postion - timing over-advanced or system performance (Bank 2)" ),
   FaultCodeData(id: '10',faultCode: "P0022",title : "A camshaft position - timing over retarded (Bank 2)" ),
   FaultCodeData(id: '11',faultCode: "P0023",title : "B camshaft position - actuator circuit (Bank 2)" ),
   FaultCodeData(id: '12',faultCode: "P0024",title : "B camshaft position - timing over advanced or system performance (Bank 2)" ),
   FaultCodeData(id: '13',faultCode: "P0025",title : "B camshaft position - timing over retaded(Bank 2)" ),
   FaultCodeData(id: '14',faultCode: "P0030",title : "H02S heater control circuit (Bank 1 sensor 1)" ),
   FaultCodeData(id: '15',faultCode: "P0031",title : "H02S heater control circuit low (Bank 1 sensor 1)" ),
   FaultCodeData(id: '16',faultCode: "P0032",title : "H02S heater control circuit high (Bank 1 sensor 1)" ),
   FaultCodeData(id: '17',faultCode: "P0033",title : "Turbo charger bypass valve control circuit" ),
   FaultCodeData(id: '18',faultCode: "P0034",title : "Turbo charger bypass valve control circuit low" ),
   FaultCodeData(id: '19',faultCode: "P0035",title : "Turbo charger bypass valve control circuit high" ),
   FaultCodeData(id: '20',faultCode: "P0036",title : "H02S heater control circuit (Bank 1 sensor 2)" ),
   FaultCodeData(id: '21',faultCode: "P0037",title : "H02S heater control circuit low (Bank 1 sensor 2)" ),
   FaultCodeData(id: '22',faultCode: "P0038",title : "H02S heater control circuit high (Bank 1 sensor 2)" ),
   FaultCodeData(id: '23',faultCode: "P0042",title : "H02S heater control circuit (Bank 1 sensor 3)" ),
   FaultCodeData(id: '24',faultCode: "P0043",title : "H02S heater control circuit Low (Bank 1 sensor 3)" ),
   FaultCodeData(id: '25',faultCode: "P0044",title : "H02S heater control circuit High (Bank 1 sensor 3)" ),
   FaultCodeData(id: '26',faultCode: "P0050",title : "H02S heater control circuit (Bank 2 sensor 1)" ),
   FaultCodeData(id: '27',faultCode: "P0051",title : "H02S heater control circuit Low (Bank 2 sensor 1)" ),
   FaultCodeData(id: '28',faultCode: "P0052",title : "H02S heater control circuit High (Bank 2 sensor 1)" ),
   FaultCodeData(id: '29',faultCode: "P0056",title : "H02S heater control circuit (Bank 2 sensor 2)" ),
   FaultCodeData(id: '30',faultCode: "P0057",title : "H02S heater control circuit Low (Bank 2 sensor 2)" ),
   FaultCodeData(id: '31',faultCode: "P0058",title : "H02S heater control circuit High (Bank 2 sensor 2)" ),
   FaultCodeData(id: '32',faultCode: "P0062",title : "H02S heater control circuit (Bank 2 sensor 3)" ),
   FaultCodeData(id: '33',faultCode: "P0063",title : "H02S heater control circuit Low (Bank 2 sensor 3)" ),
   FaultCodeData(id: '34',faultCode: "P0064",title : "H02S heater control circuit High (Bank 2 sensor 3)" ),
   FaultCodeData(id: '35',faultCode: "P0065",title : "Air assisted injector control range / performance" ),
   FaultCodeData(id: '36',faultCode: "P0066",title : "Air assisted injector control circuit or circuit low" ),
   FaultCodeData(id: '37',faultCode: "P0067",title : "Air assisted injector control circuit high" ),
   FaultCodeData(id: '38',faultCode: "P0070",title : "Ambient air temperature sensor circuit" ),
   FaultCodeData(id: '39',faultCode: "P0071",title : "Ambient air temperature sensor range/performance" ),
   FaultCodeData(id: '40',faultCode: "P0072",title : "Ambient air temperature sensor circuit low input" ),
   FaultCodeData(id: '41',faultCode: "P0073",title : "Ambient air temperature sensor circuit high input" ),
   FaultCodeData(id: '42',faultCode: "P0074",title : "Ambient air temperature sensor circuit intermittent" ),
   FaultCodeData(id: '43',faultCode: "P0075",title : "Intake valve control solenoid circuit (Bank 1)" ),
   FaultCodeData(id: '44',faultCode: "P0076",title : "Intake valve control solenoid circuit low (Bank 1)" ),
   FaultCodeData(id: '45',faultCode: "P0077",title : "Intake valve control solenoid circuit high (Bank 1)" ),
   FaultCodeData(id: '46',faultCode: "P0078",title : "Exhaust valve control solenoid circuit (Bank 1)" ),
   FaultCodeData(id: '47',faultCode: "P0079",title : "Exhaust valve control solenoid circuit low (Bank 1)" ),
   FaultCodeData(id: '48',faultCode: "P0080",title : "Exhaust valve control solenoid circuit high (Bank 1)" ),
   FaultCodeData(id: '49',faultCode: "P0081",title : "Intake valve control solenoid circuit (Bank 2)" ),
   FaultCodeData(id: '50',faultCode: "P0082",title : "Intake valve control solenoid circuit low (Bank 2)" ),
   FaultCodeData(id: '51',faultCode: "P0083",title : "Intake valve control solenoid circuit high (Bank 2)" ),
   FaultCodeData(id: '52',faultCode: "P0084",title : "Exhaust valve control solenoid circuit (Bank 2)" ),
   FaultCodeData(id: '53',faultCode: "P0085",title : "Exhaust valve control solenoid circuit low (Bank 2)" ),
   FaultCodeData(id: '54',faultCode: "P0086",title : "Exhaust valve control solenoid circuit high (Bank 2)" ),
   FaultCodeData(id: '55',faultCode: "P0030",title : "- Heated Oxygen Sensor (H02S) Heater Control Circuit Bank 1 Sensor 1" ),
   FaultCodeData(id: '56',faultCode: "P0031",title : "- Heated Oxygen Sensor (HO2S) Heater Circuit Low Voltage Bank 1 Sensor 1" ),
   FaultCodeData(id: '57',faultCode: "P0032",title : "- Heated Oxygen Sensor (HO2S) Heater Circuit High Voltage Bank 1 Sensor 1" ),
   FaultCodeData(id: '58',faultCode: "P0036",title : "- Heated Oxygen Sensor (HO2S) Heater Control Circuit Bank 1 Sensor 2" ),
   FaultCodeData(id: '59',faultCode: "P0037",title : "- Heated Oxygen Sensor (HO2S) Heater Circuit Low Voltage Bank 1 Sensor 2" ),
   FaultCodeData(id: '60',faultCode: "P0038",title : "- Heated Oxygen Sensor (HO2S) Heater Circuit High Voltage Bank 1 Sensor 2" ),
   FaultCodeData(id: '61',faultCode: "P0056",title : "- Heated Oxygen Sensor (HO2S) Heater Circuit Bank 2 Sensor 2" ),
   FaultCodeData(id: '62',faultCode: "P0057",title : "- Heated Oxygen Sensor (HO2S) Heater Circuit Low Voltage Bank 2 Sensor 2" ),
   FaultCodeData(id: '63',faultCode: "P0058",title : "- Heated Oxygen Sensor (HO2S) Heater Circuit High Voltage Bank 2 Sensor 2" ),
   FaultCodeData(id: '64',faultCode: "P0068",title : "- Throttle Body Airflow Performance (PCM)" ),
   FaultCodeData(id: '65',faultCode: "P0100",title : "MAF Sensor Circuit Insufficient Activity" ),
   FaultCodeData(id: '66',faultCode: "P0101",title : "Mass Air Flow (MAF) Sensor Performance" ),
   FaultCodeData(id: '67',faultCode: "P0102",title : "Mass Air Flow (MAF) Sensor Circuit Low Frequency" ),
   FaultCodeData(id: '68',faultCode: "P0103",title : "Mass Air Flow (MAF) Sensor Circuit High Frequency" ),
   FaultCodeData(id: '69',faultCode: "P0104",title : "Mass Air Flow Circuit Intermittent" ),
   FaultCodeData(id: '70',faultCode: "P0105",title : "MAP Sensor Circuit Insufficient Activity" ),
   FaultCodeData(id: '71',faultCode: "P0106",title : "Manifold Absolute Pressure (MAP) System Performance" ),
   FaultCodeData(id: '72',faultCode: "P0107",title : "Manifold Absolute Pressure (MAP) Sensor Circuit Low Voltage" ),
   FaultCodeData(id: '73',faultCode: "P0108",title : "Manifold Absolute Pressure (MAP) Sensor Circuit High Voltage" ),
   FaultCodeData(id: '74',faultCode: "P0109",title : "Manifold Absolute Pressure Circuit Intermittent" ),
   FaultCodeData(id: '75',faultCode: "P0110",title : "Intake Air Temperature (IAT) Sensor Circuit" ),
   FaultCodeData(id: '76',faultCode: "P0111",title : "Intake Air Temperature (IAT) Sensor Performance" ),
   FaultCodeData(id: '77',faultCode: "P0112",title : "Intake Air Temperature (IAT) Sensor Circuit Low Voltage" ),
   FaultCodeData(id: '78',faultCode: "P0113",title : "Intake Air Temperature (IAT) Sensor Circuit High Voltage" ),
   FaultCodeData(id: '79',faultCode: "P0114",title : "Intake Air Temperature Circuit Intermittent" ),
   FaultCodeData(id: '80',faultCode: "P0115",title : "Engine Coolant Temperature (ECT) Sensor Circuit" ),
   FaultCodeData(id: '81',faultCode: "P0116",title : "Engine Coolant Temperature (ECT) Sensor Performance" ),
   FaultCodeData(id: '82',faultCode: "P0117",title : "Engine Coolant Temperature (ECT) Sensor Circuit Low Voltage" ),
   FaultCodeData(id: '83',faultCode: "P0118",title : "Engine Coolant Temperature (ECT) Sensor Circuit High Voltage" ),
   FaultCodeData(id: '84',faultCode: "P0119",title : "Engine Coolant Temperature Circuit Intermittent" ),
   FaultCodeData(id: '85',faultCode: "P0120",title : "TP System Performance" ),
   FaultCodeData(id: '86',faultCode: "P0121",title : "TP Sensor Circuit Insufficient Activity" ),
   FaultCodeData(id: '87',faultCode: "P0122",title : "Throttle Position (TP) Sensor Circuit Low Voltage" ),
   FaultCodeData(id: '88',faultCode: "P0123",title : "Throttle Position (TP) Sensor Circuit High Voltage" ),
   FaultCodeData(id: '89',faultCode: "P0124",title : "Throttle Position Sensor 1 Circuit Intermittent" ),
   FaultCodeData(id: '90',faultCode: "P0125",title : "Engine Coolant Temperature (ECT) Insufficient for Closed Loop Fuel Control" ),
   FaultCodeData(id: '91 ',faultCode: "P0126",title : "Insufficient ECT for Stable Operation" ),
   FaultCodeData(id: '92 ',faultCode: "P0128",title : "Coolant Thermostat Below Thermostat Regulating Temperature" ),
   FaultCodeData(id: '93 ',faultCode: "P0130",title : "Heated Oxygen Sensor (HO2S) Circuit Closed Loop (CL) Performance Bank 1 Sensor 1" ),
   FaultCodeData(id: '94 ',faultCode: "P0131",title : "Heated Oxygen Sensor (HO2S) Circuit Low Voltage Bank 1 Sensor 1" ),
   FaultCodeData(id: '95 ',faultCode: "P0132",title : "Heated Oxygen Sensor (HO2S) Circuit High Voltage Bank 1 Sensor 1" ),
   FaultCodeData(id: '96 ',faultCode: "P0133",title : "Heated Oxygen Sensor (HO2S) Slow Response Bank 1 Sensor 1" ),
   FaultCodeData(id: '97 ',faultCode: "P0134",title : "Heated Oxygen Sensor (HO2S) Circuit Insufficient Activity Bank 1 Sensor 1" ),
   FaultCodeData(id: '98 ',faultCode: "P0135",title : "Heated Oxygen Sensor (HO2S) Heater Performance Bank 1 Sensor 1" ),
   FaultCodeData(id: '99 ',faultCode: "P0136",title : "Heated Oxygen Sensor (HO2S) Circuit Bank 1 Sensor 2" ),
   FaultCodeData(id: '100',faultCode: "P0137",title : "Heated Oxygen Sensor (HO2S) Circuit Low Voltage Bank 1 Sensor 2" ),
   FaultCodeData(id: '101',faultCode: "P0138",title : "Heated Oxygen Sensor (HO2S) Circuit High Voltage Bank 1 Sensor 2" ),
   FaultCodeData(id: '102',faultCode: "P0139",title : "Heated Oxygen Sensor (HO2S) Slow Response Bank 1 Sensor 2" ),
   FaultCodeData(id: '103',faultCode: "P0140",title : "Heated Oxygen Sensor (HO2S) Circuit Insufficient Activity Bank 1 Sensor 2" ),
   FaultCodeData(id: '104',faultCode: "P0141",title : "Heated Oxygen Sensor (HO2S) Heater Performance Bank 1 Sensor 2" ),
   FaultCodeData(id: '105',faultCode: "P0142",title : "Heated Oxygen Sensor (HO2S) Circuit Bank 1 Sensor 3" ),
   FaultCodeData(id: '106',faultCode: "P0143",title : "Heated Oxygen Sensor (HO2S) Circuit Low Voltage Bank 1 Sensor 3" ),
   FaultCodeData(id: '107',faultCode: "P0144",title : "Heated Oxygen Sensor (HO2S) Circuit High Voltage Bank 1 Sensor 3" ),
   FaultCodeData(id: '108',faultCode: "P0145",title : "Heated Oxygen Sensor (HO2S) Circuit Bank 1 Sensor 2 Slow Response" ),
   FaultCodeData(id: '109',faultCode: "P0146",title : "Heated Oxygen Sensor (HO2S) Circuit Insufficient Activity Bank 1 Sensor 3" ),
   FaultCodeData(id: '110',faultCode: "P0147",title : "Heated Oxygen Sensor (HO2S) Heater Performance Bank 1 Sensor 3" ),
   FaultCodeData(id: '111',faultCode: "P0150",title : "Heated Oxygen Sensor (HO2S) Circuit Closed Loop (CL) Performance Bank 2 Sensor 1" ),
   FaultCodeData(id: '112',faultCode: "P0151",title : "Heated Oxygen Sensor (HO2S) Circuit Low Voltage Bank 2 Sensor 1" ),
   FaultCodeData(id: '113',faultCode: "P0152",title : "Heated Oxygen Sensor (HO2S) Circuit High Voltage Bank 2 Sensor 1" ),
   FaultCodeData(id: '114',faultCode: "P0153",title : "Heated Oxygen Sensor (HO2S) Slow Response Bank 2 Sensor 1" ),
   FaultCodeData(id: '115',faultCode: "P0154",title : "Heated Oxygen Sensor (HO2S) Circuit Insufficient Activity Bank 2 Sensor 1" ),
   FaultCodeData(id: '116',faultCode: "P0155",title : "Heated Oxygen Sensor (HO2S) Heater Performance Bank 2 Sensor 1" ),
   FaultCodeData(id: '117',faultCode: "P0156",title : "Heated Oxygen Sensor (HO2S) Circuit Bank 2 Sensor 2" ),
   FaultCodeData(id: '118',faultCode: "P0157",title : "Heated Oxygen Sensor (HO2S) Circuit Low Voltage Bank 2 Sensor 2" ),
   FaultCodeData(id: '119',faultCode: "P0158",title : "Heated Oxygen Sensor (HO2S) Circuit High Voltage Bank 2 Sensor 2" ),
   FaultCodeData(id: '120',faultCode: "P0159",title : "Heated Oxygen Sensor (HO2S) Slow Response Bank 2 Sensor 2" ),
   FaultCodeData(id: '121',faultCode: "P0160",title : "Heated Oxygen Sensor (HO2S) Circuit Insufficient Activity Bank 2 Sensor 2" ),
   FaultCodeData(id: '122',faultCode: "P0161",title : "Heated Oxygen Sensor (HO2S) Heater Performance Bank 2 Sensor 2" ),
   FaultCodeData(id: '123',faultCode: "P0162",title : "Heated Oxygen Sensor (HO2S) Circuit Bank 2 Sensor 3" ),
   FaultCodeData(id: '124',faultCode: "P0163",title : "Heated Oxygen Sensor (HO2S) Circuit Bank 2 Sensor 3 Low Voltage" ),
   FaultCodeData(id: '125',faultCode: "P0164",title : "Heated Oxygen Sensor (HO2S) Circuit Bank 2 Sensor 3 High Voltage" ),
   FaultCodeData(id: '126',faultCode: "P0165",title : "Heated Oxygen Sensor (HO2S) Circuit Bank 2 Sensor 3 Slow Response" ),
   FaultCodeData(id: '127',faultCode: "P0166",title : "Heated Oxygen Sensor (HO2S) Circuit Bank 2 Sensor 3 No Activity Detected" ),
   FaultCodeData(id: '128',faultCode: "P0167",title : "Heated Oxygen Sensor (HO2S) Heater Circuit Bank 2 Sensor 3" ),
   FaultCodeData(id: '129',faultCode: "P0169",title : "Fuel Composition Sensor" ),
   FaultCodeData(id: '130',faultCode: "P0170",title : "Fuel Trim Bank 1" ),
   FaultCodeData(id: '131',faultCode: "P0171",title : "Fuel Trim System Lean Bank 1" ),
   FaultCodeData(id: '132',faultCode: "P0172",title : "Fuel Trim System Rich Bank 1" ),
   FaultCodeData(id: '133',faultCode: "P0173",title : "Fuel Trim Bank 2" ),
   FaultCodeData(id: '134',faultCode: "P0174",title : "Fuel Trim System Lean Bank 2" ),
   FaultCodeData(id: '135',faultCode: "P0175",title : "Fuel Trim System Rich Bank 2" ),
   FaultCodeData(id: '136',faultCode: "P0176",title : "Fuel Composition Sensor Circuit" ),
   FaultCodeData(id: '137',faultCode: "P0177",title : "Fuel Composition Sensor Circuit Performance" ),
   FaultCodeData(id: '138',faultCode: "P0178",title : "Fuel Composition Sensor Circuit Low Voltage" ),
   FaultCodeData(id: '139',faultCode: "P0179",title : "Fuel Composition Sensor Circuit High Voltage" ),
   FaultCodeData(id: '140',faultCode: "P0180",title : "Fuel Temperature Sensor 1 Circuit" ),
   FaultCodeData(id: '141',faultCode: "P0181",title : "Fuel Temp. Sensor 1 Circuit Performance" ),
   FaultCodeData(id: '142',faultCode: "P0182",title : "Fuel Temperature Sensor Circuit Low Voltage" ),
   FaultCodeData(id: '143',faultCode: "P0183",title : "Fuel Temperature Sensor Circuit High Voltage" ),
   FaultCodeData(id: '144',faultCode: "P0184",title : "Fuel Temperature Sensor 1 Circuit Intermittent" ),
   FaultCodeData(id: '145',faultCode: "P0185",title : "Fuel Temperature Sensor 2 Circuit" ),
   FaultCodeData(id: '146',faultCode: "P0186",title : "Fuel Temp. Sensor 2 Circuit Performance" ),
   FaultCodeData(id: '147',faultCode: "P0187",title : "Fuel Temperature Sensor 2 Circuit Low Voltage" ),
   FaultCodeData(id: '148',faultCode: "P0188",title : "Fuel Temperature Sensor 2 Circuit High Voltage" ),
   FaultCodeData(id: '149',faultCode: "P0189",title : "Fuel Temperature Sensor 2 Circuit Intermittent" ),
   FaultCodeData(id: '150',faultCode: "P0190",title : "Fuel Rail Pressure Sensor Circuit" ),
   FaultCodeData(id: '151',faultCode: "P0191",title : "Fuel Rail Pressure Sensor Circuit Performance" ),
   FaultCodeData(id: '152',faultCode: "P0192",title : "Fuel Rail Pressure Sensor Circuit Low Voltage" ),
   FaultCodeData(id: '153',faultCode: "P0193",title : "Fuel Rail Pressure Sensor Circuit High Voltage" ),
   FaultCodeData(id: '154',faultCode: "P0194",title : "Fuel Rail Pressure Sensor Circuit Intermittent" ),
   FaultCodeData(id: '155',faultCode: "P0195",title : "Engine Oil Temperature Sensor" ),
   FaultCodeData(id: '156',faultCode: "P0196",title : "Engine Oil Temperature Sensor Performance" ),
   FaultCodeData(id: '157',faultCode: "P0197",title : "Engine Oil Temperature Sensor Low Voltage" ),
   FaultCodeData(id: '158',faultCode: "P0198",title : "Engine Oil Temperature Sensor High Voltage" ),
   FaultCodeData(id: '159',faultCode: "P0199",title : "Engine Oil Temperature Sensor Intermittent" ),
   FaultCodeData(id: '160',faultCode: "P0200",title : "Injector Control Circuit" ),
   FaultCodeData(id: '161',faultCode: "P0201",title : "Injector 1 Control Circuit" ),
   FaultCodeData(id: '162',faultCode: "P0202",title : "Injector 2 Control Circuit" ),
   FaultCodeData(id: '163',faultCode: "P0203",title : "Injector 3 Control Circuit" ),
   FaultCodeData(id: '164',faultCode: "P0204",title : "Injector 4 Control Circuit" ),
   FaultCodeData(id: '165',faultCode: "P0205",title : "Injector 5 Control Circuit" ),
   FaultCodeData(id: '166',faultCode: "P0206",title : "Injector 6 Control Circuit" ),
   FaultCodeData(id: '167',faultCode: "P0207",title : "Injector 7 Control Circuit" ),
   FaultCodeData(id: '168',faultCode: "P0208",title : "Injector 8 Control Circuit" ),
   FaultCodeData(id: '169',faultCode: "P0209",title : "Injector 9 Control Circuit" ),
   FaultCodeData(id: '170',faultCode: "P0210",title : "Injector 10 Control Circuit" ),
   FaultCodeData(id: '171',faultCode: "P0211",title : "Injector 11 Control Circuit" ),
   FaultCodeData(id: '172',faultCode: "P0212",title : "Injector 12 Control Circuit" ),
   FaultCodeData(id: '173',faultCode: "P0213",title : "Cold Start Injector 1" ),
   FaultCodeData(id: '174',faultCode: "P0214",title : "Cold Start Injector 2" ),
   FaultCodeData(id: '175',faultCode: "P0215",title : "Engine Shutoff Control Circuit" ),
   FaultCodeData(id: '176',faultCode: "P0216",title : "Injection Timing Control Circuit" ),
   FaultCodeData(id: '177',faultCode: "P0217",title : "Engine Overtemp Condition" ),
   FaultCodeData(id: '178',faultCode: "P0218",title : "Transmission Fluid Overtemperature" ),
   FaultCodeData(id: '179',faultCode: "P0219",title : "Engine Overspeed Condition" ),
   FaultCodeData(id: '180',faultCode: "P0220",title : "APP Sensor 2 Circuit" ),
   FaultCodeData(id: '181',faultCode: "P0221",title : "APP (Throttle Position) Sensor 2 Circuit Performance" ),
   FaultCodeData(id: '182',faultCode: "P0222",title : "APP (Throttle Position) Sensor 2 Circuit Low Voltage" ),
   FaultCodeData(id: '183',faultCode: "P0223",title : "APP (Throttle Position) Sensor 2 Circuit High Voltage" ),
   FaultCodeData(id: '184',faultCode: "P0224",title : "Throttle Position Sensor 2 Intermittent" ),
   FaultCodeData(id: '185',faultCode: "P0225",title : "APP Sensor 3 Circuit" ),
   FaultCodeData(id: '186',faultCode: "P0226",title : "APP Sensor 3 Circuit Performance" ),
   FaultCodeData(id: '187',faultCode: "P0227",title : "APP Sensor 3 Circuit Low Voltage" ),
   FaultCodeData(id: '188',faultCode: "P0228",title : "APP Sensor 3 Circuit High Voltage" ),
   FaultCodeData(id: '189',faultCode: "P0229",title : "Throttle Position Sensor 3 Intermittent" ),
   FaultCodeData(id: '190',faultCode: "P0230",title : "Fuel Pump Relay Control Circuit" ),
   FaultCodeData(id: '191',faultCode: "P0231",title : "Fuel Pump Feedback Circuit Low Voltage" ),
   FaultCodeData(id: '192',faultCode: "P0232",title : "Fuel Pump Feedback Circuit High Voltage" ),
   FaultCodeData(id: '193',faultCode: "P0233",title : "Fuel Pump Secondary Circuit Intermittent" ),
   FaultCodeData(id: '194',faultCode: "P0234",title : "Turbocharger Engine Overboost Condition" ),
   FaultCodeData(id: '195',faultCode: "P0235",title : "Turbocharger Boost Sensor 1 Circuit" ),
   FaultCodeData(id: '196',faultCode: "P0236",title : "Turbocharger Boost System" ),
   FaultCodeData(id: '197',faultCode: "P0237",title : "Turbocharger Boost Sensor Circuit Low Voltage" ),
   FaultCodeData(id: '198',faultCode: "P0238",title : "Turbocharger Boost Sensor Circuit High Voltage" ),
   FaultCodeData(id: '199',faultCode: "P0239",title : "Turbocharger Boost Sensor 2 Circuit" ),

   FaultCodeData(id: '200',faultCode: "P0240",title : "Turbocharger Boost Sensor 2 Performance" ),
   FaultCodeData(id: '201',faultCode: "P0241",title : "Turbocharger Boost Sensor 2 Circuit Low Voltage" ),
   FaultCodeData(id: '202',faultCode: "P0242",title : "Turbocharger Boost Sensor 2 Circuit High Voltage" ),
   FaultCodeData(id: '203',faultCode: "P0243",title : "Turbocharger Wastegate Solenoid 1" ),
   FaultCodeData(id: '204',faultCode: "P0244",title : "Turbocharger Wastegate Solenoid 1 Performance" ),
   FaultCodeData(id: '205',faultCode: "P0245",title : "Turbocharger Wastegate Solenoid 1 Low Voltage" ),
   FaultCodeData(id: '206',faultCode: "P0246",title : "Turbocharger Wastegate Solenoid 1 High Voltage" ),
   FaultCodeData(id: '207',faultCode: "P0247",title : "Turbocharger Wastegate Solenoid 2" ),
   FaultCodeData(id: '208',faultCode: "P0248",title : "Turbocharger Wastegate Solenoid 2 Performance" ),
   FaultCodeData(id: '209',faultCode: "P0249",title : "Turbocharger Wastegate Solenoid 2 Low Voltage" ),
   FaultCodeData(id: '210',faultCode: "P0250",title : "Turbocharger Wastegate Solenoid 2 High Voltage" ),
   FaultCodeData(id: '211',faultCode: "P0251",title : "Injection Pump Fuel Metering Control A Malfunction (Cam/Rotor/Injector)" ),
   FaultCodeData(id: '212',faultCode: "P0252",title : "Injection Pump Fuel Metering Control A Range/Performance (Cam/Rotor/Injector)" ),
   FaultCodeData(id: '213',faultCode: "P0253",title : "Injection Pump Fuel Metering Control A Low (Cam/Rotor/Injector)" ),
   FaultCodeData(id: '214',faultCode: "P0254",title : "Injection Pump Fuel Metering Control A High (Cam/Rotor/Injector)" ),
   FaultCodeData(id: '215',faultCode: "P0255",title : "Injection Pump Fuel Metering Control A Intermittent (Cam/Rotor/Injector)" ),
   FaultCodeData(id: '216',faultCode: "P0256",title : "Injection Pump Fuel Metering Control B Malfunction (Cam/Rotor/Injector)" ),
   FaultCodeData(id: '217',faultCode: "P0257",title : "Injection Pump Fuel Metering Control B Range/Performance (Cam/Rotor/Injector)" ),
   FaultCodeData(id: '218',faultCode: "P0258",title : "Injection Pump Fuel Metering Control B Low (Cam/Rotor/Injector)" ),
   FaultCodeData(id: '219',faultCode: "P0259",title : "Injection Pump Fuel Metering Control B High (Cam/Rotor/Injector)" ),
   FaultCodeData(id: '220',faultCode: "P0260",title : "Injection Pump Fuel Metering Control B Intermittent (Cam/Rotor/Injector)" ),
   FaultCodeData(id: '221',faultCode: "P0261",title : "Cylinder 1 Injector Circuit Low" ),
   FaultCodeData(id: '222',faultCode: "P0262",title : "Cylinder 1 Injector Circuit High" ),
   FaultCodeData(id: '223',faultCode: "P0263",title : "Cylinder 1 Contribution/Balance Fault" ),
   FaultCodeData(id: '224',faultCode: "P0264",title : "Cylinder 2 Injector Circuit Low" ),
   FaultCodeData(id: '225',faultCode: "P0265",title : "Cylinder 2 Injector Circuit High" ),
   FaultCodeData(id: '226',faultCode: "P0266",title : "Cylinder 2 Contribution/Balance Fault" ),
   FaultCodeData(id: '227',faultCode: "P0267",title : "Cylinder 3 Injector Circuit Low" ),
   FaultCodeData(id: '228',faultCode: "P0268",title : "Cylinder 3 Injector Circuit High" ),
   FaultCodeData(id: '229',faultCode: "P0269",title : "Cylinder 3 Contribution/Balance Fault" ),
   FaultCodeData(id: '230',faultCode: "P0270",title : "Cylinder 4 Injector Circuit Low" ),
   FaultCodeData(id: '231',faultCode: "P0271",title : "Cylinder 4 Injector Circuit High" ),
   FaultCodeData(id: '232',faultCode: "P0272",title : "Cylinder 4 Contribution/Balance Fault" ),
   FaultCodeData(id: '233',faultCode: "P0273",title : "Cylinder 5 Injector Circuit Low" ),
   FaultCodeData(id: '234',faultCode: "P0274",title : "Cylinder 5 Injector Circuit High" ),
   FaultCodeData(id: '235',faultCode: "P0275",title : "Cylinder 5 Contribution/Balance Fault" ),
   FaultCodeData(id: '236',faultCode: "P0276",title : "Cylinder 6 Injector Circuit Low" ),
   FaultCodeData(id: '237',faultCode: "P0277",title : "Cylinder 6 Injector Circuit High" ),
   FaultCodeData(id: '238',faultCode: "P0278",title : "Cylinder 6 Contribution/Balance Fault" ),
   FaultCodeData(id: '239',faultCode: "P0279",title : "Cylinder 7 Injector Circuit Low" ),
   FaultCodeData(id: '240',faultCode: "P0280",title : "Cylinder 7 Injector Circuit High" ),
   FaultCodeData(id: '241',faultCode: "P0281",title : "Cylinder 7 Contribution/Balance Fault" ),
   FaultCodeData(id: '242',faultCode: "P0282",title : "Cylinder 8 Injector Circuit Low" ),
   FaultCodeData(id: '243',faultCode: "P0283",title : "Cylinder 8 Injector Circuit High" ),
   FaultCodeData(id: '244',faultCode: "P0284",title : "Cylinder 8 Contribution/Balance Fault" ),
   FaultCodeData(id: '245',faultCode: "P0285",title : "Cylinder 9 Injector Circuit Low" ),
   FaultCodeData(id: '246',faultCode: "P0286",title : "Cylinder 9 Injector Circuit High" ),
   FaultCodeData(id: '247',faultCode: "P0287",title : "Cylinder 9 Contribution/Balance Fault" ),
   FaultCodeData(id: '248',faultCode: "P0288",title : "Cylinder 10 Injector Circuit Low" ),
   FaultCodeData(id: '249',faultCode: "P0289",title : "Cylinder 10 Injector Circuit High" ),
   FaultCodeData(id: '250',faultCode: "P0290",title : "Cylinder 10 Contribution/Balance Fault" ),
   FaultCodeData(id: '251',faultCode: "P0291",title : "Cylinder 11 Injector Circuit Low" ),
   FaultCodeData(id: '252',faultCode: "P0292",title : "Cylinder 11 Injector Circuit High" ),
   FaultCodeData(id: '253',faultCode: "P0293",title : "Cylinder 11 Contribution/Balance Fault" ),
   FaultCodeData(id: '254',faultCode: "P0294",title : "Cylinder 12 Injector Circuit Low" ),
   FaultCodeData(id: '255',faultCode: "P0295",title : "Cylinder 12 Injector Circuit High" ),
   FaultCodeData(id: '256',faultCode: "P0296",title : "Cylinder 12 Contribution/Range Fault" ),
   FaultCodeData(id: '257',faultCode: "P0300",title : "Engine Misfire Detected" ),
   FaultCodeData(id: '258',faultCode: "P0301",title : "Cylinder 1 Misfire Detected" ),
   FaultCodeData(id: '259',faultCode: "P0302",title : "Cylinder 2 Misfire Detected" ),
   FaultCodeData(id: '260',faultCode: "P0303",title : "Cylinder 3 Misfire Detected" ),
   FaultCodeData(id: '261',faultCode: "P0304",title : "Cylinder 4 Misfire Detected" ),
   FaultCodeData(id: '262',faultCode: "P0305",title : "Cylinder 5 Misfire Detected" ),
   FaultCodeData(id: '263',faultCode: "P0306",title : "Cylinder 6 Misfire Detected" ),
   FaultCodeData(id: '264',faultCode: "P0307",title : "Cylinder 7 Misfire Detected" ),
   FaultCodeData(id: '265',faultCode: "P0308",title : "Cylinder 8 Misfire Detected" ),
   FaultCodeData(id: '266',faultCode: "P0309",title : "Cylinder 9 Misfire Detected" ),
   FaultCodeData(id: '267',faultCode: "P0310",title : "Cylinder 10 Misfire Detected" ),
   FaultCodeData(id: '268',faultCode: "P0311",title : "Cylinder 11 Misfire Detected" ),
   FaultCodeData(id: '269',faultCode: "P0312",title : "Cylinder 12 Misfire Detected" ),
   FaultCodeData(id: '270',faultCode: "P0313",title : "Misfire Detected With Low Fuel Level" ),
   FaultCodeData(id: '271',faultCode: "P0315",title : "Crankshaft position (CKP) system variation values are not stored in the PCM memory" ),
   FaultCodeData(id: '272',faultCode: "P0318",title : "Rough Road Sensor Circuit" ),
   FaultCodeData(id: '273',faultCode: "P0320",title : "Ignition/Distributor Engine Speed Input Circuit Malfunction" ),
   FaultCodeData(id: '274',faultCode: "P0321",title : "Ignition/Distributor Engine Speed Input Circuit Range/Performance" ),
   FaultCodeData(id: '275',faultCode: "P0322",title : "IC Module 4X Reference Circuit No Frequency" ),
   FaultCodeData(id: '276',faultCode: "P0323",title : "Ignition/Distributor Engine Speed Input Circuit Intermittent" ),
   FaultCodeData(id: '277',faultCode: "P0324",title : "Knock Sensor (KS) Module Performance" ),
   FaultCodeData(id: '278',faultCode: "P0325",title : "PCM Knock Sensor Circuit" ),
   FaultCodeData(id: '279',faultCode: "P0326",title : "Knock Sensor Circuit Excessive Spark Retard" ),
   FaultCodeData(id: '280',faultCode: "P0327",title : "Knock Sensor Circuit Low Voltage" ),
   FaultCodeData(id: '281',faultCode: "P0328",title : "Knock Sensor 1 Circuit High Input (Bank 1 or Single Sensor)" ),
   FaultCodeData(id: '282',faultCode: "P0329",title : "Knock Sensor 1 Circuit Intermittent (Bank 1 or Single Sensor)" ),
   FaultCodeData(id: '283',faultCode: "P0330",title : "Knock Sensor (KS) Circuit Bank 2" ),
   FaultCodeData(id: '284',faultCode: "P0331",title : "Knock Sensor 2 Circuit Range/Performance (Bank 2)" ),
   FaultCodeData(id: '285',faultCode: "P0332",title : "Knock Sensor 2 Circuit Low Input (Bank 2)" ),
   FaultCodeData(id: '286',faultCode: "P0333",title : "Knock Sensor 2 Circuit High Input (Bank 2)" ),
   FaultCodeData(id: '287',faultCode: "P0334",title : "Knock Sensor 2 Circuit Intermittent (Bank 2)" ),
   FaultCodeData(id: '288',faultCode: "P0335",title : "CKP Sensor A Circuit Performance" ),
   FaultCodeData(id: '289',faultCode: "P0336",title : "Crankshaft Position (CKP) Sensor A Performance" ),
   FaultCodeData(id: '290',faultCode: "P0337",title : "Crankshaft Position (CKP) Sensor Circuit Low Duty Cycle" ),
   FaultCodeData(id: '291',faultCode: "P0338",title : "Crankshaft Position (CKP) Sensor Circuit High Duty Cycle" ),
   FaultCodeData(id: '292',faultCode: "P0339",title : "Crankshaft Position (CKP) Sensor Circuit Intermittent" ),
   FaultCodeData(id: '293',faultCode: "P0340",title : "Camshaft Position (CMP) Sensor Circuit" ),
   FaultCodeData(id: '294',faultCode: "P0341",title : "Camshaft Position (CMP) Sensor Performance" ),
   FaultCodeData(id: '295',faultCode: "P0342",title : "Camshaft Position Sensor Circuit Low Input" ),
   FaultCodeData(id: '296',faultCode: "P0343",title : "Camshaft Position Sensor Circuit High Input" ),
   FaultCodeData(id: '297',faultCode: "P0344",title : "Camshaft Position Sensor Circuit Intermittent" ),
   FaultCodeData(id: '298',faultCode: "P0350",title : "Ignition Coil Primary/Secondary Circuit Malfunction" ),
   FaultCodeData(id: '299',faultCode: "P0351",title : "Ignition Coil 1 Control Circuit" ),
  /* FaultCodeData(id: '300',faultCode: "P0352",title : "Ignition Coil 2 Control Circuit" ),
   FaultCodeData(id: '301',faultCode: "P0353",title : "Ignition Coil 3 Control Circuit" ),
   FaultCodeData(id: '302',faultCode: "P0354",title : "Ignition Coil 4 Control Circuit" ),
   FaultCodeData(id: '303',faultCode: "P0355",title : "Ignition Coil 5 Control Circuit" ),
   FaultCodeData(id: '304',faultCode: "P0356",title : "Ignition Coil 6 Control Circuit" ),
   FaultCodeData(id: '305',faultCode: "P0357",title : "Ignition Coil 7 Control Circuit" ),
   FaultCodeData(id: '306',faultCode: "P0358",title : "Ignition Coil 8 Control Circuit" ),
   FaultCodeData(id: '307',faultCode: "P0359",title : "Ignition Coil I Primary/Secondary Circuit Malfunction" ),
   FaultCodeData(id: '308',faultCode: "P0360",title : "Ignition Coil J Primary/Secondary Circuit Malfunction" ),
   FaultCodeData(id: '309',faultCode: "P0361",title : "Ignition Coil K Primary/Secondary Circuit Malfunction" ),
   FaultCodeData(id: '310',faultCode: "P0362",title : "Ignition Coil L Primary/Secondary Circuit Malfunction" ),
   FaultCodeData(id: '311',faultCode: "P0370",title : "Timing Reference High Resolution Signal A Malfunction" ),
   FaultCodeData(id: '312',faultCode: "P0371",title : "IC 24X Reference Circuit Too Many Pulses" ),
   FaultCodeData(id: '313',faultCode: "P0372",title : "IC 24X Reference Circuit Missing Pulses" ),
   FaultCodeData(id: '314',faultCode: "P0373",title : "Timing Reference High Resolution Signal A Intermittent/Erratic Pulses" ),
   FaultCodeData(id: '315',faultCode: "P0374",title : "Timing Reference High Resolution Signal A No Pulses" ),
   FaultCodeData(id: '316',faultCode: "P0375",title : "Timing Reference High Resolution Signal B Malfunction" ),
   FaultCodeData(id: '317',faultCode: "P0376",title : "Timing Reference High Resolution Signal B Too Many Pulses" ),
   FaultCodeData(id: '318',faultCode: "P0377",title : "Timing Reference High Resolution Signal B Too Few Pulses" ),
   FaultCodeData(id: '319',faultCode: "P0378",title : "Timing Reference High Resolution Signal B Intermittent/Erratic Pulses" ),
   FaultCodeData(id: '320',faultCode: "P0379",title : "Timing Reference High Resolution Signal B No Pulses" ),
   FaultCodeData(id: '321',faultCode: "P0380",title : "Glow Plug/Heater Circuit A Malfunction" ),
   FaultCodeData(id: '322',faultCode: "P0381",title : "Glow Plug/Heater Indicator Circuit Malfunction" ),
   FaultCodeData(id: '323',faultCode: "P0382",title : "Exhaust Gas Recirculation Flow Malfunction" ),
   FaultCodeData(id: '324',faultCode: "P0385",title : "Crankshaft Position (CKP) Sensor B Circuit" ),
   FaultCodeData(id: '325',faultCode: "P0386",title : "Crankshaft Position (CKP) Sensor B Performance" ),
   FaultCodeData(id: '326',faultCode: "P0387",title : "Crankshaft Position Sensor B Circuit Low Input" ),
   FaultCodeData(id: '327',faultCode: "P0388",title : "Crankshaft Position Sensor B Circuit High Input" ),
   FaultCodeData(id: '328',faultCode: "P0389",title : "Crankshaft Position Sensor B Circuit Intermittent" ),
   FaultCodeData(id: '329',faultCode: "P0400",title : "Exhaust Gas Recirculation Flow Malfunction" ),
   FaultCodeData(id: '330',faultCode: "P0401",title : "Exhaust Gas Recirculation (EGR) Flow Insufficient" ),
   FaultCodeData(id: '331',faultCode: "P0402",title : "Exhaust Gas Recirculation Flow Excessive Detected" ),
   FaultCodeData(id: '332',faultCode: "P0403",title : "Exhaust Gas Recirculation (EGR) Solenoid Control Circuit" ),
   FaultCodeData(id: '333',faultCode: "P0404",title : "Exhaust Gas Recirculation (EGR) Open Position Performance" ),
   FaultCodeData(id: '334',faultCode: "P0405",title : "Exhaust Gas Recirculation (EGR) Position Sensor Circuit Low Voltage" ),
   FaultCodeData(id: '335',faultCode: "P0406",title : "Exhaust Gas Recirculation Sensor A Circuit High" ),
   FaultCodeData(id: '336',faultCode: "P0407",title : "Exhaust Gas Recirculation Sensor B Circuit Low" ),
   FaultCodeData(id: '337',faultCode: "P0408",title : "Exhaust Gas Recirculation Sensor B Circuit High" ),
   FaultCodeData(id: '338',faultCode: "P0410",title : "Secondary Air Injection (AIR) System" ),
   FaultCodeData(id: '339',faultCode: "P0411",title : "Secondary Air Injection (AIR) System" ),
   FaultCodeData(id: '340',faultCode: "P0412",title : "Secondary Air Injection (AIR) Solenoid Relay Control Circuit Bank 1" ),
   FaultCodeData(id: '341',faultCode: "P0413",title : "Secondary Air Injection System Switching Valve A Circuit Open" ),
   FaultCodeData(id: '342',faultCode: "P0414",title : "Secondary Air Injection System Switching Valve A Circuit Shorted" ),
   FaultCodeData(id: '343',faultCode: "P0415",title : "Secondary Air Injection System Switching Valve B Circuit Malfunction" ),
   FaultCodeData(id: '344',faultCode: "P0416",title : "Secondary Air Injection System Switching Valve B Circuit Open" ),
   FaultCodeData(id: '345',faultCode: "P0417",title : "Secondary Air Injection System Switching Valve B Circuit Shorted" ),
   FaultCodeData(id: '346',faultCode: "P0418",title : "Secondary Air Injection (AIR) Pump Relay Control Circuit Bank 1" ),
   FaultCodeData(id: '347',faultCode: "P0419",title : "Secondary Air Injection (AIR) Pump Relay Control Circuit Bank 2" ),
   FaultCodeData(id: '348',faultCode: "P0420",title : "Catalyst System Low Efficiency" ),
   FaultCodeData(id: '349',faultCode: "P0421",title : "Warm Up Catalyst Efficiency Below Threshold (Bank 1)" ),
   FaultCodeData(id: '350',faultCode: "P0422",title : "Catalyst System Low Efficiency Bank 1" ),
   FaultCodeData(id: '354',faultCode: "P0431",title : "Warm Up Catalyst Efficiency Below Threshold (Bank 2)" ),
   FaultCodeData(id: '355',faultCode: "P0432",title : "Catalyst System Low Efficiency Bank 2" ),
   FaultCodeData(id: '356',faultCode: "P0433",title : "Heated Catalyst Efficiency Below Threshold (Bank 2)" ),
   FaultCodeData(id: '357',faultCode: "P0434",title : "Heated Catalyst Temperature Below Threshold (Bank 2)" ),
   FaultCodeData(id: '358',faultCode: "P0440",title : "Evaporative Emission (EVAP) System" ),
   FaultCodeData(id: '359',faultCode: "P0441",title : "Evaporative Emission Control System Incorrect Purge Flow" ),
   FaultCodeData(id: '360',faultCode: "P0442",title : "Evaporative Emission (EVAP) System Small Leak Detected" ),
   FaultCodeData(id: '361',faultCode: "P0443",title : "EVAP Purge Solenoid Valve 1 Control Circuit" ),
   FaultCodeData(id: '362',faultCode: "P0444",title : "Evaporative Emission Control System Purge Control Valve Circuit Open" ),
   FaultCodeData(id: '363',faultCode: "P0445",title : "Evaporative Emission Control System Purge Control Valve Circuit Shorted" ),
   FaultCodeData(id: '364',faultCode: "P0446",title : "EVAP Vent Solenoid Valve Control System" ),
   FaultCodeData(id: '365',faultCode: "P0447",title : "Evaporative Emission Control System Vent Control Circuit Open" ),
   FaultCodeData(id: '366',faultCode: "P0448",title : "Evaporative Emission Control System Vent Control Circuit Shorted" ),
   FaultCodeData(id: '367',faultCode: "P0449",title : "Evaporative Emission (EVAP) Vent Solenoid Control Circuit" ),
   FaultCodeData(id: '368',faultCode: "P0450",title : "Fuel Tank Pressure Sensor Circuit" ),
   FaultCodeData(id: '369',faultCode: "P0451",title : "Evaporative Emission Control System Pressure Sensor Range/Performance" ),
   FaultCodeData(id: '370',faultCode: "P0452",title : "Fuel Tank Pressure Sensor Circuit Low Voltage" ),
   FaultCodeData(id: '371',faultCode: "P0453",title : "Fuel Tank Pressure Sensor Circuit High Voltage" ),
   FaultCodeData(id: '372',faultCode: "P0454",title : "Evaporative Emission Control System Pressure Sensor Intermittent" ),
   FaultCodeData(id: '373',faultCode: "P0455",title : "Evaporative Emission (EVAP) System Leak Detected" ),
   FaultCodeData(id: '374',faultCode: "P0460",title : "Fuel Level Sensor Circuit" ),
   FaultCodeData(id: '375',faultCode: "P0461",title : "Fuel Level Sensor Performance" ),
   FaultCodeData(id: '376',faultCode: "P0462",title : "Fuel Level Sensor Circuit Low Voltage" ),
   FaultCodeData(id: '377',faultCode: "P0463",title : "Fuel Level Sensor Circuit High Voltage" ),
   FaultCodeData(id: '378',faultCode: "P0464",title : "Fuel Level Sensor Circuit Intermittent" ),
   FaultCodeData(id: '379',faultCode: "P0465",title : "Purge Flow Sensor Circuit Malfunction" ),
   FaultCodeData(id: '380',faultCode: "P0466",title : "Purge Flow Sensor Circuit Range/Performance" ),
   FaultCodeData(id: '381',faultCode: "P0467",title : "Purge Flow Sensor Circuit Low Input" ),
   FaultCodeData(id: '382',faultCode: "P0468",title : "Purge Flow Sensor Circuit High Input" ),
   FaultCodeData(id: '383',faultCode: "P0469",title : "Purge Flow Sensor Circuit Intermittent" ),
   FaultCodeData(id: '384',faultCode: "P0470",title : "Exhaust Pressure Sensor Malfunction" ),
   FaultCodeData(id: '385',faultCode: "P0471",title : "Exhaust Pressure Sensor Range/Performance" ),
   FaultCodeData(id: '386',faultCode: "P0472",title : "Exhaust Pressure Sensor Low" ),
   FaultCodeData(id: '387',faultCode: "P0473",title : "Exhaust Pressure Sensor High" ),
   FaultCodeData(id: '388',faultCode: "P0474",title : "Exhaust Pressure Sensor Intermittent" ),
   FaultCodeData(id: '389',faultCode: "P0475",title : "Exhaust Pressure Control Valve Malfunction" ),*/
];
